[package]
name = "peach"
version = "0.1.0"
authors = ["Timothy Davis <tmthydvs@gmail.com>"]
edition = "2018"

[dependencies]
euclid = "0.20.6"
lyon_tessellation = "0.14.2"
wgpu = "0.4.0"
winit = "0.20.0-alpha4"
