[package]
name = "peach"
version = "0.3.0"
authors = ["Timothy Davis <tmthydvs@gmail.com>"]
edition = "2018"

description = "Sandbox engine for Rust, inspired by Processing"

license = "MIT"
repository = "https://github.com/flmng0/peach"
readme = "README.md"

keywords = ["processing", "sandbox", "drawing"]

[dependencies]
thiserror = "1.0"

winit = "0.22"

palette = "0.5"
lyon_tessellation = "0.15"
