[package]
name = "peach"
version = "0.1.0"
authors = ["Timothy Davis <tmthydvs@gmail.com>"]
edition = "2018"

[dependencies]
euclid = "0.20.6"
shaderc = "0.6.1"
lyon_tessellation = "0.14.2"
wgpu = "0.4.0"
wgpu-native = "0.4.0"
winit = "0.20.0-alpha4"

[dev-dependencies]
approx = "0.3.2"
