[package]
name = "peach"
version = "0.1.0"
authors = ["Timothy Davis <tmthydvs@gmail.com>"]
edition = "2018"

[dependencies]
euclid = "0.20"
shaderc = "0.6"
lyon_tessellation = "0.14"
log = "0.4"
wgpu = "0.4"
wgpu-native = "0.4"
winit = "0.20.0-alpha5"

[dev-dependencies]
approx = "0.3"
env_logger = "0.7"
